// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXgbzJX579nyAabO1aq23L_ECGpKSRo1M',
    appId: '1:920524685017:android:1f97b0e9a6ca8b3622c8c8',
    messagingSenderId: '920524685017',
    projectId: 'chat-app-ad928',
    storageBucket: 'chat-app-ad928.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjYbffpcJdXR7DnUZakmcpdtYTlm1h4bc',
    appId: '1:920524685017:ios:4f96a923cc8a185222c8c8',
    messagingSenderId: '920524685017',
    projectId: 'chat-app-ad928',
    storageBucket: 'chat-app-ad928.appspot.com',
    androidClientId: '920524685017-1hgabmcj217kn3tilge4feo2o85lkhir.apps.googleusercontent.com',
    iosClientId: '920524685017-k4dn36lit26mje3nfirqk4i7c6bsin13.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
